[package]
name = "postcard"
version = "0.2.1"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/jamesmunns/postcard"
description = "A (TODO), no_std, serde compatible message library for Rust"
license = "MIT OR Apache-2.0"

[dependencies]

[dependencies.heapless]
version = "0.4"
features = ["serde"]

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]

[dependencies.byteorder]
version = "1.3"
default-features = false

[dependencies.cobs]
git = "https://github.com/ferrous-systems/cobs.rs"
rev = "running-enc-dec"
default-features = false
