[package]
name = "postcard"
version = "0.0.0"
authors = ["James Munns <james.munns@ferrous-systems.com>"]
edition = "2018"
readme = "README.md"
repository = "https://github.com/jamesmunns/postcard"
description = "A (TODO), no_std, serde compatible message library for Rust"
license = "MIT OR Apache-2.0"

[dependencies]
